# $CZ_{01}CZ_{02}$ gate  

In [1]:
from system import *
#s1 = system('t',MMA=True)
s1 = load_object('t')

# $\Delta_{E\gamma} \rightarrow \ \Delta_{E\gamma}\, C^n \qquad \Delta_{e\gamma} \rightarrow \ \Delta_{e\gamma}\, C^m$

In [2]:
n = 1
m = 0

# Effective Hamiltonian Matrix obtain in $C \longrightarrow \infty$ limit

In [3]:
var('gamma','DE','De','g','g_f','Omega','v','gamma_f','gamma_g',domain='positive')
var('DEt',domain='complex',  latex_name =r'\tilde{\Delta }_E')
var('Det',domain='complex',  latex_name =r'\tilde{\Delta }_e')
var('DEg',domain='positive',  latex_name =r'\Delta_{E\gamma}')
var('Deg',domain='positive',  latex_name =r'\Delta_{e\gamma}')
var('kappa_c','kappa_b',domain='positive')
var('C',domain='positive')
var('c_k',domain='positive',  latex_name =r'c_\kappa')

eff_hamiltonian_tayl = sg.copy( s1.eff_hamiltonian.parent().zero())
for diag in s1.pos_gs:
    print(f'Calculating {diag} out of {s1.pos_gs}...')
    #Take only one of the compl conj terms. Switch maybe second 0 to 1
    min_expr_len = 10**10
    for term in range(1):
        b = s1.eff_hamiltonian[diag,diag]

        b = b.operands()[1].operands()[term]
        #b = b.subs(DE=+0.5*I*gamma_f + 0.5*I*gamma_g + DEt*gamma)
        #b = b.subs(De=+0.5*I*gamma   +Det*gamma)
        b = b.subs(DE=DEg*gamma*C^n)
        b = b.subs(De=Deg*gamma*C^m)
        
        var('R_f',domain='positive')#ratio  (g_f/g)^2
        b = b.subs(g_f=g*sqrt(R_f))

        var('R_v',domain='positive',  latex_name =r'R_{\nu}') #ratio (v/g)^2
        b = b.subs(v=g*sqrt(R_v))

        var('r_b',domain='positive')
        b = b.subs(kappa_b=gamma/r_b)
        
        var('r_f',domain='positive',latex_name =r'r_f')
        b = b.subs(gamma_f=gamma*r_f)
        
        var('r_g',domain='positive',latex_name =r'r_g')
        b = b.subs(gamma_g=gamma*r_g)
        
        b = b.subs(g = sqrt(C*gamma*kappa_c)) 
        b = b.subs(r_b = c_k/C)

        b = b*gamma  #Omega has to be substituted with Omega/gamma


        b = b._mathematica_().Factor()._sage_()
        b = MMA_simplify(b)#,full=True)
        #holds the smallest expression
        if len(str(b))<min_expr_len:
            min_expr_len = len(str(b))
            h_eff = b
  
    q = h_eff.subs(C=1/x)
    q = MMA_simplify(q)
    tayl = q._mathematica_().Series((x,0,1)).Normal()._sage_()
    tayl = tayl.subs(x=1/C)
    
    #tayl =  (tayl + conjugate(tayl))/2      # try with + conjugate_transp

    #taylr = taylr.expand()
    #tayl = MMA_simplify(tayl,full=True)
    eff_hamiltonian_tayl[diag,diag] = Omega^2/gamma * tayl

print('\nReal part of H_eff in ground state subspace taylor expanded in 1/C: ')
show(symround(eff_hamiltonian_tayl[s1.pos_gs,s1.pos_gs],digits=4))

eff_hamiltonian_tayl = (eff_hamiltonian_tayl[s1.pos_gs,s1.pos_gs] + conjugate(eff_hamiltonian_tayl[s1.pos_gs,s1.pos_gs]))/2

Calculating 0 out of [0, 1, 2, 3, 4, 5, 6, 7]...
Calculating 1 out of [0, 1, 2, 3, 4, 5, 6, 7]...
Calculating 2 out of [0, 1, 2, 3, 4, 5, 6, 7]...
Calculating 3 out of [0, 1, 2, 3, 4, 5, 6, 7]...
Calculating 4 out of [0, 1, 2, 3, 4, 5, 6, 7]...
Calculating 5 out of [0, 1, 2, 3, 4, 5, 6, 7]...
Calculating 6 out of [0, 1, 2, 3, 4, 5, 6, 7]...
Calculating 7 out of [0, 1, 2, 3, 4, 5, 6, 7]...

Real part of H_eff in ground state subspace taylor expanded in 1/C: 


[(R_v^3*c_k^3 + 0.5625*R_v^2*c_k^2 + 0.09375*R_v*c_k + 0.003906)*Omega^2/(((R_v^3*c_k^3 + 0.5625*R_v^2*c_k^2 + 0.09375*R_v*c_k + 0.003906)*DEg + (-0.5000*I*R_v^3*c_k^3 - 0.6250*I*R_v^2*c_k^2 - 0.1562*I*R_v*c_k - 0.007812*I)*R_f)*C*gamma)                                                                                                                                                                                                                                            0                                                                                                                                                                                                                                            0                                                                                                                                                                                                                                            0                                                                                                                                                                                                                                            0                                                                                                                                                                                                                                            0                                                                                                                                                                                                                                            0                                                                                                                                                                                                                                            0]
[                                                                                                                                                                                                                                           0                                      (R_v^3*c_k^3 + 1.250*R_v^2*c_k^2 + 0.3125*R_v*c_k + 0.01562)*Omega^2/(((R_v^3*c_k^3 + 1.250*R_v^2*c_k^2 + 0.3125*R_v*c_k + 0.01562)*DEg + (-I*R_v^2*c_k^2 - 0.5000*I*R_v*c_k - 0.03125*I)*R_f)*C*gamma)                                                                                                                                                                                                                                            0                                                                                                                                                                                                                                            0                                                                                                                                                                                                                                            0                                                                                                                                                                                                                                            0                                                                                                                                                                                                                                            0                                                                                                                                                                                                                                            0]
[                                                                                                                                                                                                           

# Parameter manipulation

In [4]:
#isolate parameters
a = eff_hamiltonian_tayl[0,0]
a = MMA_simplify(a,full=True)

b = eff_hamiltonian_tayl[1,1]
b = MMA_simplify(b,full=True)

c = eff_hamiltonian_tayl[3,3]
c = MMA_simplify(c,full=True)

d = eff_hamiltonian_tayl[4,4]
d = MMA_simplify(d,full=True)

e = eff_hamiltonian_tayl[5,5]
e = MMA_simplify(e,full=True)

f = eff_hamiltonian_tayl[7,7]
f = MMA_simplify(f,full=True)

a = MMA_simplify(a.numerator().expand()) /  MMA_simplify(a.denominator().expand())
b = MMA_simplify(b.numerator().expand()) /  MMA_simplify(b.denominator().expand())
#c = MMA_simplify(c.numerator().expand()) /  MMA_simplify(c.denominator().expand())

d = MMA_simplify(d.numerator().expand()) /  MMA_simplify(d.denominator().expand())
e = MMA_simplify(e.numerator().expand()) /  MMA_simplify(e.denominator().expand())
f = MMA_simplify(f.numerator().expand()) /  MMA_simplify(f.denominator().expand())

In [5]:
tg = 3*np.pi/(e+a-b-d)

eq1 = (a-2*b+c)*tg
eq1 = MMA_simplify(eq1)
var('x',domain = 'real')
eq1 = eq1.subs(R_v=x/c_k) 

eq2 = (3*a-2*b-d+f)*tg
eq2 = MMA_simplify(eq2)
eq2 = eq2.subs(R_v=x/c_k)

In [6]:
#search for simultaneous roots
tol =1e-12
rf=1
de=1
valp=10
p = -1
while True:
    #rf = rf-10^p
    de = de+10^p
    eq1s = eq1.subs(R_f =rf , DEg=de)
    eq = eq1s-2*pi == 0 #2*pi ??
    sol = solve(eq,x)
    sol = sol[0].rhs()
    sol = (sol).roots(x, ring=RR, multiplicities=False)
    #sol = eq.roots(x, ring=RR, multiplicities=False)
    for i in sol:
        if i>0:
            x1=i
    eq2s = eq2.subs(R_f =rf ,DEg=de)
    val = np.mod(float(eq2s.subs(x=x1)) , 2*np.pi)
    if abs(val)<tol:
        break
    if abs(val)>abs(valp):
        print(f'precision: {p}')
        print(rf.n(),de.n(),valp)
        #rf = rf+10^p
        de = de-10^p
        p = p-1
    else:
        valp=val
print('x1 , R_f D_{Eg}')
show(x1)
show(rf.n())
show(de.n())

precision: -1
1.00000000000000 1.30000000000000 2.207266137319351
precision: -2
1.00000000000000 1.23000000000000 0.18682883390788874
precision: -3
1.00000000000000 1.22200000000000 0.08499972994047766
precision: -4
1.00000000000000 1.22190000000000 0.0034810507205733643
precision: -5
1.00000000000000 1.22184000000000 0.00042314229862938646
precision: -6
1.00000000000000 1.22183500000000 1.541594362208798e-05
precision: -7
1.00000000000000 1.22183420000000 5.22276872771954e-06
precision: -8
1.00000000000000 1.22183416000000 1.2618110645234992e-07
precision: -9
1.00000000000000 1.22183415200000 2.4249423802302772e-08
precision: -10
1.00000000000000 1.22183415130000 3.862972164370149e-09
precision: -11
1.00000000000000 1.22183415124000 8.051230793171271e-10
precision: -12
1.00000000000000 1.22183415123800 9.134737410931848e-11
precision: -13
1.00000000000000 1.22183415123790 9.919176591210999e-12
x1 , R_f D_{Eg}


1.01014311134038

1.00000000000000

1.22183415123789

In [7]:
#substitute results
rot = sg.copy( eff_hamiltonian_tayl.parent().zero())
ent = sg.copy( eff_hamiltonian_tayl.parent().zero())


t = abs( tg.subs(R_f =rf ,DEg=de,R_v=x1/c_k) )
t1 = (a-b).subs(R_f =rf ,DEg=de,R_v=x1/c_k)*t
t2 = (a-b).subs(R_f =rf ,DEg=de,R_v=x1/c_k)*t
t3 = (a-d).subs(R_f =rf ,DEg=de,R_v=x1/c_k) *t

r_add = [0, t1, t2, t1+t2, t3, t3+t1, t3+t2, t3+t1+t2 ]
en = [a,b,b,c,d,e,e,f]
for i in range(8):
    rot[i,i] = exp(I*r_add[i])
    ent[i,i] = exp( (en[i]-a).subs(R_f =rf ,DEg=de,R_v=x1/c_k)*t*sg.I)

U = rot*ent

U = U.subs(t = pi/(e+a-b-d).subs(R_f =rf ,DEg=de,R_v=x1/c_k))
Un = U.n(digits=1)
print('Final matrix')
show(((Un.n(digits=1))+conjugate((Un.n(digits=1))))/2)

print('with  complex error')
show(((Un.n(digits=1))-conjugate((Un.n(digits=1))))/2)

Final matrix


[ 1.0 0.00 0.00 0.00 0.00 0.00 0.00 0.00]
[0.00  1.0 0.00 0.00 0.00 0.00 0.00 0.00]
[0.00 0.00  1.0 0.00 0.00 0.00 0.00 0.00]
[0.00 0.00 0.00  1.0 0.00 0.00 0.00 0.00]
[0.00 0.00 0.00 0.00  1.0 0.00 0.00 0.00]
[0.00 0.00 0.00 0.00 0.00 -1.0 0.00 0.00]
[0.00 0.00 0.00 0.00 0.00 0.00 -1.0 0.00]
[0.00 0.00 0.00 0.00 0.00 0.00 0.00  1.0]

with  complex error


[      0.00       0.00       0.00       0.00       0.00       0.00       0.00       0.00]
[      0.00       0.00       0.00       0.00       0.00       0.00       0.00       0.00]
[      0.00       0.00       0.00       0.00       0.00       0.00       0.00       0.00]
[      0.00       0.00       0.00  5.4e-14*I       0.00       0.00       0.00       0.00]
[      0.00       0.00       0.00       0.00       0.00       0.00       0.00       0.00]
[      0.00       0.00       0.00       0.00       0.00 -3.3e-16*I       0.00       0.00]
[      0.00       0.00       0.00       0.00       0.00       0.00 -3.3e-16*I       0.00]
[      0.00       0.00       0.00       0.00       0.00       0.00       0.00 -2.8e-15*I]

In [8]:
t

118.355092310716*C*gamma/Omega^2

In [182]:
np.mod(float(t3),2*np.pi)/np.pi

0.10778978351038017

# Lindblau Operators

Choose which of the Lindblau operators to view and which non zero element of it

In [13]:
lind_op_number = len(s1.lindblau_list)

eff_lind_taylor = []
eff_lind = []
eff_lind_coeff = []
for lind_op in range(lind_op_number):
    print(f'{lind_op} out of {lind_op_number-1}')
    eff_lind_taylor.append([])
    eff_lind.append([])
    L_matrix = s1.eff_lindblau_list[lind_op]
    L_nonzeros = []
    L_nonzeros_pos = []
    for i in  range(L_matrix.nrows()):
        for j in  range(L_matrix.ncols()):
            if not L_matrix[i,j].is_zero():
                L_nonzeros.append(L_matrix[i,j])
                L_nonzeros_pos.append((i,j))
    eff_lind_coeff.append(s1.L_coeffs[lind_op])
    for which in range(len(L_nonzeros)):

        L_elem = L_nonzeros[which]

        #L_elem = L_elem.subs(DE=+0.5*I*gamma_f + 0.5*I*gamma_g + DEt*gamma)
        #L_elem = L_elem.subs(De=+0.5*I*gamma   +Det*gamma)
        L_elem = L_elem.subs(DE=DEg*gamma*C^n)
        L_elem = L_elem.subs(De=Deg*gamma*C^m)
        #COUPLINGS

        L_elem = L_elem.subs(g_f=g*sqrt(R_f))

        L_elem = L_elem.subs(v=g*sqrt(R_v))

        #ABSORBTIONS
        L_elem = L_elem.subs(kappa_b=gamma/r_b)

        L_elem = L_elem.subs(gamma_g=gamma*r_g)

        L_elem = L_elem.subs(gamma_f=gamma*r_f)

        L_elem = L_elem.subs(g = sqrt(C*gamma*kappa_c)) 
        L_elem = L_elem.subs(r_b = c_k/C)
        
        L_elem = L_elem._mathematica_().Factor()._sage_()


        L_elem = MMA_simplify(L_elem)#,full=True)

        L_elem = SR(str(L_elem).replace('Sqrt','sqrt'))
        
        L_elem_show = symround(L_elem)
        
        eff_lind[lind_op].append(L_elem_show)
        
        var('x')
        q = L_elem.subs(C=1/x)
        q = MMA_simplify(q)
        tayl = q._mathematica_().Series((x,0,1)).Normal()._sage_()
        tayl = tayl.subs(x=1/C)
        tayl = SR(str(tayl).replace('Sqrt','sqrt'))
        tayl_show = symround(tayl)
        
        eff_lind_taylor[-1].append(tayl_show)

0 out of 8
symround: Deleted coefficient -5.1e-16
symround: Deleted coefficient 1.4e-14
symround: Deleted coefficient 9.8e-15
symround: Deleted coefficient -8.9e-16
symround: Deleted coefficient 6.2e-15
symround: Deleted coefficient 1.1e-14
symround: Deleted coefficient 8.9e-15
symround: Deleted coefficient 6.7e-16
symround: Deleted coefficient 6.2e-15
symround: Deleted coefficient 1.1e-14
symround: Deleted coefficient 8.9e-15
symround: Deleted coefficient 6.7e-16
1 out of 8
2 out of 8
3 out of 8
4 out of 8
symround: Deleted coefficient -8.9e-16
symround: Deleted coefficient -8.9e-16
symround: Deleted coefficient -2.2e-16
symround: Deleted coefficient 6.2e-15
symround: Deleted coefficient 7.1e-15
symround: Deleted coefficient 4.4e-15
symround: Deleted coefficient -8.9e-16
symround: Deleted coefficient -1.1e-15
symround: Deleted coefficient -1.1e-16
symround: Deleted coefficient -8.9e-16
symround: Deleted coefficient -1.1e-15
symround: Deleted coefficient -1.1e-16
5 out of 8
symround: D

# See results

In [ ]:
#show((eff_lind_taylor[2][3]))

In [ ]:
#show(eff_lind[0][3])

In [14]:
lindop = 3
a = eff_lind_taylor[lindop][0]
err = t_g*a*conjugate(a)
err = SR(str(MMA_simplify( err,full=False )).replace('Sqrt','sqrt')).simplify()
show( symround( err ) )
print(f'coeff:')
show(eff_lind_coeff[lindop])

symround: Deleted coefficient 2.2e-17
symround: Deleted coefficient 1.1e-17
symround: Deleted coefficient 2.8e-18
symround: Deleted coefficient 1.7e-19


((R_v^3.5*c_k^3 + 0.88*R_v^2.5*c_k^2 + 0.16*R_v^1.5*c_k + 0.0078*sqrt(R_v))*sqrt(C)*R_f^1.5 + (-1.5*I*R_v^3.5*c_k^3 - 0.69*I*R_v^2.5*c_k^2 - 0.094*I*R_v^1.5*c_k - 0.0039*I*sqrt(R_v))*DEg*sqrt(R_f))*(-0.62*(R_v^3.5*c_k^3 + 0.88*R_v^2.5*c_k^2 + 0.16*R_v^1.5*c_k + 0.0078*sqrt(R_v))*sqrt(C)*R_f^1.5 - 0.62*(1.5*I*R_v^3.5*c_k^3 + 0.69*I*R_v^2.5*c_k^2 + 0.094*I*R_v^1.5*c_k + 0.0039*I*sqrt(R_v))*DEg*sqrt(R_f))*(R_v*c_k + 0.25)^2*(R_v*c_k + 0.12)^2*c_k/((DEg*R_v^6*c_k^6 + 1.4*DEg*R_v^5*c_k^5 + 0.81*DEg*R_v^4*c_k^4 + 0.24*DEg*R_v^3*c_k^3 + 0.039*DEg*R_v^2*c_k^2 + 0.0031*DEg*R_v*c_k + 0.000097*DEg)*(R_v^2*c_k^2 + 0.75*R_v*c_k + 0.062)^4*sqrt(C)*R_f^2)

coeff:


sqrt(kappa_b)

In [ ]:
(err).has(C)

In [185]:
print(f'R_f ={rf} \nDEg={de}\nR_v={x1}/c_k')

R_f =1 
DEg=122183415123789/100000000000000
R_v=1.01014311134038/c_k
