# Many Variables  GHZ

In [1]:
from system import *
#s1 = system('o-o-x-o-',MMA=True,ManyVariables = True)
s1 = load_object('GHZ')

# Effective Hamiltonian Matrix obtain 

In [20]:
phi_val = np.pi/180 * 30
n = 1/2

total_indices = s1.variable_index

var('De1', domain='positive')
var('Deg1', domain='positive' , latex_name =r'{{\Delta e}}_{{  1}}^\gamma')
var('De2', domain='positive')
var('Deg2', domain='positive' , latex_name =r'{{\Delta e}}_{{  2}}^\gamma')
var('De3', domain='positive')
var('Deg3', domain='positive' , latex_name =r'{{\Delta e}}_{{  3}}^\gamma')    

var('gamma','DE','De','g','g_f','Omega','v','gamma_f','gamma_g','phi',domain='positive')
var('DEg', domain='positive' , latex_name =r'{{\Delta E}}^\gamma')
var('kappa_c','kappa_b',domain='positive')
var('C',domain='positive')
var('c',domain='positive',  latex_name =r'c')
var('r_f',domain='positive',latex_name =r'r_f')
var('r_g',domain='positive',latex_name =r'r_g')
var('R_f',domain='positive')#ratio  (g_f/g)^2
eff_hamiltonian_tayl = sg.copy( s1.eff_hamiltonian.parent().zero())
for diag in s1.pos_gs:
    print(f'Calculating {diag} out of {s1.pos_gs}...')

    b = s1.eff_hamiltonian[diag,diag]
    b = b.subs(phi = phi_val)

     
    b = b.subs(DE = DEg*gamma)
    
    b = b.subs(De1 = Deg1*gamma*C^n) #sqrt C scaling!?
    
    b = b.subs(De2 = Deg2*gamma) #MAKE ZERO
    b = b.subs(De3 = Deg3*gamma) #MAKE ZERO   
    b = b.subs(g_f=g*(R_f)^(1/2))

    b = b.subs(gamma_f=gamma*r_f)


    b = b.subs(gamma_g=gamma*r_g)

    b = b.subs(g = (C*gamma*kappa_c)^(1/2)) 
    
    b = b.subs(v = (c*kappa_b*kappa_c)^(1/2) )


    #Substitutions
    #b = b.subs(c=np.pi,R_f=2.1,Deg=np.e,DEg=np.sqrt(5),r_g=np.sqrt(3),r_f=np.sqrt(2), phi=phi_val) 
    #b = b.subs(phi=phi_val)

    #b = b._mathematica_().Factor()._sage_()
    #b = b._mathematica_().Together()._sage_()

        
    b = SR(str(b).replace('Sqrt','sqrt'))

    
    eff_hamiltonian_tayl[diag,diag] = b  # Omega^2/gamma *
    
print('\n H_eff in ground state subspace: ')
#show(symround(eff_hamiltonian_tayl[s1.pos_gs,s1.pos_gs],digits=3))


eff_hamiltonian_tayl = eff_hamiltonian_tayl[s1.pos_gs,s1.pos_gs] 

Calculating 0 out of [0, 1, 18, 19, 48, 49, 66, 67]...
Calculating 1 out of [0, 1, 18, 19, 48, 49, 66, 67]...
Calculating 18 out of [0, 1, 18, 19, 48, 49, 66, 67]...
Calculating 19 out of [0, 1, 18, 19, 48, 49, 66, 67]...
Calculating 48 out of [0, 1, 18, 19, 48, 49, 66, 67]...
Calculating 49 out of [0, 1, 18, 19, 48, 49, 66, 67]...
Calculating 66 out of [0, 1, 18, 19, 48, 49, 66, 67]...
Calculating 67 out of [0, 1, 18, 19, 48, 49, 66, 67]...

 H_eff in ground state subspace: 


# Parameter manipulation

In [31]:

a = eff_hamiltonian_tayl[0,0]
#a = symround( MMA_simplify(a,full=False) ,digits = 14)
b = eff_hamiltonian_tayl[1,1]
#b = symround(MMA_simplify(b,full=False),digits = 14)
c = eff_hamiltonian_tayl[3,3]
#c = symround(MMA_simplify(c,full=False),digits = 14)
d = eff_hamiltonian_tayl[4,4]
#d = symround(MMA_simplify(d,full=False),digits = 14)
e = eff_hamiltonian_tayl[5,5]
#e = symround(MMA_simplify(e,full=False),digits = 14)
f = eff_hamiltonian_tayl[7,7]
#f = symround(MMA_simplify(f,full=False),digits = 14)

In [95]:
#show(MMA_simplify(c))

# Gate time

In [96]:
denom = a+e-b-d

denom = denom._mathematica_().Together()._sage_()
denom = SR(str(denom).replace('Sqrt','sqrt'))
t_g = 3*np.pi/denom



expr = (2*a - 2*b - d + f )#._mathematica_().Together()._sage_() #a=b=0
expr = expr*t_g

KeyboardInterrupt: 

In [134]:
t_test = (SR(str((MMA_simplify(t_g.subs(c=C,R_f=1,r_g=1,r_f=1,gamma=1,Deg1=1)))).replace('Sqrt','sqrt')))
print('Time Numerator')
#print(t_test.numerator().expand())
print('Time Denominator')
#print(t_test.denominator().expand())

Time Numerator
Time Denominator


In [3]:
c_val = 1000
expr_plot = expr.subs(c=c_val,C=100*c_val,R_f=1,r_g=0.1,r_f=0.1)
expr_plot = MMA_simplify(expr_plot,full=True)

#show(expr_plot)

#plot(abs(expr_plot)/(2*np.pi),(Deg1,-40,40),gridlines='minor' )

NameError: name 'expr' is not defined

In [7]:
expr_plot.subs(Deg1=5)/np.pi

1.78771230631476 - 1.83787004129158e-11*I

# NOTES

- We found it possible for:  

`phi_val = 0
c_val = 10000
expr_plot = expr.subs(c=c_val,C=100*c_val,R_f=1,r_g=0.1,r_f=0.1)`

with and without  sqrt scaling of Deg, but with 3pi rotation 

- Many possibilities from other `phi_val`

# Lindblau Operators no $C \longrightarrow \infty$ limit

Choose which of the Lindblau operators to view and which non zero element of it

In [40]:
lind_op_number = len(s1.lindblau_list)

eff_lind_taylor = []
eff_lind = []
eff_lind_coeff = []
for lind_op in range(lind_op_number):
    print(f'{lind_op} out of {lind_op_number-1}')
    eff_lind_taylor.append([])
    eff_lind.append([])
    L_matrix = s1.eff_lindblau_list[lind_op]
    L_nonzeros = []
    L_nonzeros_pos = []
    for i in  range(L_matrix.nrows()):
        for j in  range(L_matrix.ncols()):
            if not str(symround(L_matrix[i,j]))==str(0):
                L_nonzeros.append(L_matrix[i,j])
                L_nonzeros_pos.append((i,j))
    eff_lind_coeff.append(s1.L_coeffs[lind_op])
    
    for which in range(len(L_nonzeros)):

        L_elem = L_nonzeros[which]
        b = L_elem
        
        b = b._mathematica_().ReplaceAll(f'DE->DEg*gamma*C^({n})')._sage_()
        #b = b.subs(DE = DEg*gamma*C^n)
        
        b = b._mathematica_().ReplaceAll(f'De1->Deg1*gamma*C^({n})')._sage_()
        #b = b.subs(De1 = Deg1*gamma*C^n) #sqrt C scaling!?
        
        b = b._mathematica_().ReplaceAll(f'De2->Deg2*gamma*C^({n})')._sage_()
        #b = b.subs(De2 = Deg2*gamma*C^n) #MAKE ZERO
        
        b = b._mathematica_().ReplaceAll(f'De3->Deg2*gamma*C^({n})')._sage_()
        #b = b.subs(De3 = Deg3*gamma*C^n) #MAKE ZERO  
        
        #b = b.subs(phi = phi_val)
        
        #b = MMA_simplify(b)
        
        #b = b._mathematica_().ReplaceAll('g_f->g*(R_f)^(1/2)')._sage_()
        b = b.subs(g_f=g*(R_f)^(1/2))

        b = b._mathematica_().ReplaceAll('gamma_f->gamma*r_f')._sage_()
        #b = b.subs(gamma_f=gamma*r_f)

        b = b._mathematica_().ReplaceAll('gamma_g->gamma*r_g')._sage_()
        #b = b.subs(gamma_g=gamma*r_g)
        
        #b = b._mathematica_().ReplaceAll("g-> (C*gamma*kappa_c)^(1/2)")._sage_()
        b = b.subs(g = (C*gamma*kappa_c)^(1/2)) 
        
        b = b._mathematica_().ReplaceAll('v->(c*kappa_b*kappa_c)^(1/2)')._sage_()
        
        b = b.subs(c=C)
        
        b = SR(str(b).replace('Sqrt','sqrt'))
        
        eff_lind[lind_op].append(b)
        
print('\n Done!')

0 out of 12
1 out of 12
2 out of 12
3 out of 12
4 out of 12
5 out of 12
6 out of 12
7 out of 12
8 out of 12
9 out of 12
10 out of 12
11 out of 12
12 out of 12

 Done!


# See results

In [47]:
lindop = 7
pos = 7

err = eff_lind[lindop][pos].subs(kappa_b=1.79, R_f=2.1,Deg1=np.sqrt(2)*C^m,Deg2=np.e*C^m,DEg=np.sqrt(5)*C^m,r_g=np.sqrt(3),gamma=0.3,r_f=0.1*np.sqrt(2), phi=np.pi/10,gamma_f=1.45,gamma_g=3)

err = err._mathematica_().Together()._sage_() 
err = SR(str(( err)).replace('Sqrt','sqrt'))
#err = SR(str(MMA_simplify( err,full=False )).replace('Sqrt','sqrt')).simplify()
show( symround( err ,digits=1) )
print(f'coeff:')
show(eff_lind_coeff[lindop])

symround: Deleted coefficient -6.4e-32
symround: Deleted coefficient 3.8e-27
symround: Deleted coefficient 8.6e-28
symround: Deleted coefficient -4.7e-19
symround: Deleted coefficient -3.5e-21
symround: Deleted coefficient -5.0e-21


(2.6*C^24 + (10. - 54.*I)*C^23 - (206*I + 480)*C^22 + (2240*I - 1712)*C^21 + (7744*I + 5696)*C^20 - (6336*I - 20480)*C^19 - (32000*I - 3488)*C^18 - (19200*I + 27136)*C^17 + (8960*I - 23040)*C^16 + (13312*I - 3904)*C^15 + (4992*I + 3264)*C^14 + (360*I + 2016)*C^13 - (320*I - 464)*C^12 - (123*I - 27)*C^11 - (11. + 20.*I)*C^10 - (3.2 + 1.3*I)*C^9 - (0.40 - 0.12*I)*C^8 - (0.025 - 0.033*I)*C^7 - (0.00018 - 0.0032*I)*C^6 + (0.000092 + 0.00017*I)*C^5 + (7.3e-6 + 4.5e-6*I)*C^4 + (2.6e-7 + 2.0e-8*I)*C^3 + (4.7e-9 - 1.7e-9*I)*C^2 + (3.3e-11 - 3.0e-11*I)*C)*Omega/((C^11 + (2.9 - 11.*I)*C^10 - (38. + 24.*I)*C^9 - (64. - 48.*I)*C^8 + (12. + 58.*I)*C^7 + (22. + 7.9*I)*C^6 + (4.5 - 3.0*I)*C^5 + (0.12 - 0.76*I)*C^4 - (0.036 + 0.057*I)*C^3 - (0.0031 + 0.0014*I)*C^2 - 0.000069*C)*(C^4 + (0.38 - 3.8*I)*C^3 - (0.71 + 1.1*I)*C^2 - (0.20 + 0.12*I)*C - 0.011 - 0.0031*I)^3*(C - 0.18*I)*(C - 3.3*I))

coeff:


sqrt(gamma_g)

In [48]:
#show(symround(err).operands()[2].operands())

In [49]:
show(symround(err._mathematica_().Numerator()._sage_().expand()))
#show(symround(err.numerator().expand()))

symround: Deleted coefficient -6.4e-32
symround: Deleted coefficient 3.8e-27
symround: Deleted coefficient 8.6e-28


2.6*C^24*Omega + (10. - 54.*I)*C^23*Omega - (206*I + 480)*C^22*Omega + (2240*I - 1712)*C^21*Omega + (7744*I + 5696)*C^20*Omega - (6336*I - 20480)*C^19*Omega - (32000*I - 3488)*C^18*Omega - (19200*I + 27136)*C^17*Omega + (8960*I - 23040)*C^16*Omega + (13312*I - 3904)*C^15*Omega + (4992*I + 3264)*C^14*Omega + (360*I + 2016)*C^13*Omega - (320*I - 464)*C^12*Omega - (123*I - 27)*C^11*Omega - (11. + 20.*I)*C^10*Omega - (3.2 + 1.3*I)*C^9*Omega - (0.40 - 0.12*I)*C^8*Omega - (0.025 - 0.033*I)*C^7*Omega - (0.00018 - 0.0032*I)*C^6*Omega + (0.000092 + 0.00017*I)*C^5*Omega + (7.3e-6 + 4.5e-6*I)*C^4*Omega + (2.6e-7 + 2.0e-8*I)*C^3*Omega + (4.7e-9 - 1.7e-9*I)*C^2*Omega + (3.3e-11 - 3.0e-11*I)*C*Omega

In [ ]:
den = err._mathematica_().Denominator()._sage_().expand()
#den = SR(str(MMA_simplify( den,full=False )).replace('Sqrt','sqrt')).simplify()
show(symround(den))

In [41]:
#plot(abs(err*conjugate(err)),(C,1,500))

In [42]:
#substitute results
rot = sg.copy( eff_hamiltonian_tayl.parent().zero())
ent = sg.copy( eff_hamiltonian_tayl.parent().zero())


t =  t_g.subs(c=c_val,C=100*c_val,R_f=1,r_g=0.1,r_f=0.1,Deg1=0.0012) 


t1 = (a-b).subs(c=c_val,C=100*c_val,R_f=1,r_g=0.1,r_f=0.1,Deg1=0.0012) *t
t2 = (a-b).subs(c=c_val,C=100*c_val,R_f=1,r_g=0.1,r_f=0.1,Deg1=0.0012) *t
t3 = (a-d).subs(c=c_val,C=100*c_val,R_f=1,r_g=0.1,r_f=0.1,Deg1=0.0012)  *t

r_add = [0, t1, t2, t1+t2, t3, t3+t1, t3+t2, t3+t1+t2 ]
en = [a,b,b,c,d,e,e,f]
for i in range(8):
    rot[i,i] = exp(I*r_add[i])
    ent[i,i] = exp( (en[i]-a).subs(c=c_val,C=100*c_val,R_f=1,r_g=0.1,r_f=0.1,Deg1=0.0012) *t*sg.I)

U = rot*ent

U = U.subs(t = pi/(e+a-b-d).subs(c=c_val,C=100*c_val,R_f=1,r_g=0.1,r_f=0.1,Deg1=0.0012) )
U = MMA_simplify(U)
Un = U.n(digits=1)
print('Final matrix')
show(((Un.n(digits=1))+conjugate((Un.n(digits=1))))/2)

print('with  complex error')
show(((Un.n(digits=1))-conjugate((Un.n(digits=1))))/2)

Final matrix


[ 1.0 0.00 0.00 0.00 0.00 0.00 0.00 0.00]
[0.00  1.0 0.00 0.00 0.00 0.00 0.00 0.00]
[0.00 0.00  1.0 0.00 0.00 0.00 0.00 0.00]
[0.00 0.00 0.00  1.0 0.00 0.00 0.00 0.00]
[0.00 0.00 0.00 0.00  1.0 0.00 0.00 0.00]
[0.00 0.00 0.00 0.00 0.00 -1.0 0.00 0.00]
[0.00 0.00 0.00 0.00 0.00 0.00 -1.0 0.00]
[0.00 0.00 0.00 0.00 0.00 0.00 0.00  1.0]

with  complex error


[     0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00]
[     0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00]
[     0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00]
[     0.00      0.00      0.00 2.6e-12*I      0.00      0.00      0.00      0.00]
[     0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00]
[     0.00      0.00      0.00      0.00      0.00 5.5e-12*I      0.00      0.00]
[     0.00      0.00      0.00      0.00      0.00      0.00 5.5e-12*I      0.00]
[     0.00      0.00      0.00      0.00      0.00      0.00      0.00   0.032*I]

In [20]:
#phi_val = np.pi/180 * 30
n = 0

total_indices = s1.variable_index

var('De1', domain='positive')
var('Deg1', domain='positive' , latex_name =r'{{\Delta e}}_{{  1}}^\gamma')
var('De2', domain='positive')
var('Deg2', domain='positive' , latex_name =r'{{\Delta e}}_{{  2}}^\gamma')
var('De3', domain='positive')
var('Deg3', domain='positive' , latex_name =r'{{\Delta e}}_{{  3}}^\gamma')    

var('gamma','DE','De','g','g_f','Omega','v','gamma_f','gamma_g','phi',domain='positive')
var('DEg', domain='positive' , latex_name =r'{{\Delta E}}^\gamma')
var('kappa_c','kappa_b',domain='positive')
var('C',domain='positive')
var('c',domain='positive',  latex_name =r'c')
var('r_f',domain='positive',latex_name =r'r_f')
var('r_g',domain='positive',latex_name =r'r_g')
var('R_f',domain='positive')#ratio  (g_f/g)^2
eff_hamiltonian_tayl = sg.copy( s1.eff_hamiltonian.parent().zero())
for diag in s1.pos_gs:
    print(f'Calculating {diag} out of {s1.pos_gs}...')
    min_expr_len = 10**10
    for term in range(1):
        b = s1.eff_hamiltonian[diag,diag]
        b = b.operands()[1].operands()[term]
        if len(str(b))<10: #we isolated Omega^2 instead of one of the conjugate pairs
            b = s1.eff_hamiltonian[diag,diag].operands()[0].operands()[term]
        
        b = b._mathematica_().ReplaceAll(f'DE->DEg*gamma*C^({n})')._sage_()
        #b = b.subs(DE = DEg*gamma*C^n)
        
        b = b._mathematica_().ReplaceAll(f'De1->Deg1*gamma*C^({n})')._sage_()
        #b = b.subs(De1 = Deg1*gamma*C^n) #sqrt C scaling!?
        
        b = b._mathematica_().ReplaceAll(f'De2->Deg2*gamma*C^({n})')._sage_()
        #b = b.subs(De2 = Deg2*gamma*C^n) #MAKE ZERO
        
        b = b._mathematica_().ReplaceAll(f'De3->Deg2*gamma*C^({n})')._sage_()
        #b = b.subs(De3 = Deg3*gamma*C^n) #MAKE ZERO  
        
        #b = b.subs(phi = phi_val)
        
        #b = MMA_simplify(b)
        
        #b = b._mathematica_().ReplaceAll('g_f->g*(R_f)^(1/2)')._sage_()
        b = b.subs(g_f=g*(R_f)^(1/2))

        b = b._mathematica_().ReplaceAll('gamma_f->gamma*r_f')._sage_()
        #b = b.subs(gamma_f=gamma*r_f)

        b = b._mathematica_().ReplaceAll('gamma_g->gamma*r_g')._sage_()
        #b = b.subs(gamma_g=gamma*r_g)
        
        #b = b._mathematica_().ReplaceAll("g-> (C*gamma*kappa_c)^(1/2)")._sage_()
        b = b.subs(g = (C*gamma*kappa_c)^(1/2)) 
        
        b = b._mathematica_().ReplaceAll('v->(c*kappa_b*kappa_c)^(1/2)')._sage_()
        #b = b.subs(v = (c*kappa_b*kappa_c)^(1/2) )
        
        

        #Substitutions
        #b = b.subs(c=np.pi,R_f=2.1,Deg=np.e,DEg=np.sqrt(5),r_g=np.sqrt(3),r_f=np.sqrt(2), phi=phi_val) 
        #b = b.subs(phi=phi_val)

        #b = b._mathematica_().Factor()._sage_()
        #b = b._mathematica_().Together()._sage_()


        b = SR(str(b).replace('Sqrt','sqrt'))
        if len(str(b))<min_expr_len:
            min_expr_len = len(str(b))
            h_eff = b
    
    h_eff = h_eff.subs(c=C)
    h_eff = MMA_simplify(h_eff)
    '''
    h_eff = SR(str(h_eff).replace('Sqrt','sqrt'))
    var('x')
    h_eff = h_eff.subs(C=1/x)
    h_eff = MMA_simplify(h_eff)
    h_eff = h_eff._mathematica_().Series((x,0,1)).Normal()._sage_()
    h_eff = h_eff.subs(x=1/C)
    '''
    h_eff = SR(str(h_eff).replace('Sqrt','sqrt'))
    eff_hamiltonian_tayl[diag,diag] = h_eff  * Omega^2 / 2

print('\n Done! ')
#show(symround(eff_hamiltonian_tayl[s1.pos_gs,s1.pos_gs],digits=3))


eff_hamiltonian_tayl_temp = eff_hamiltonian_tayl[s1.pos_gs,s1.pos_gs] 

eff_hamiltonian_tayl = eff_hamiltonian_tayl_temp
a = eff_hamiltonian_tayl[0,0]
#a = symround( MMA_simplify(a,full=False) ,digits = 14)
b = eff_hamiltonian_tayl[1,1]
#b = symround(MMA_simplify(b,full=False),digits = 14)
c = eff_hamiltonian_tayl[3,3]
#c = symround(MMA_simplify(c,full=False),digits = 14)
d = eff_hamiltonian_tayl[4,4]
#d = symround(MMA_simplify(d,full=False),digits = 14)
e = eff_hamiltonian_tayl[5,5]
#e = symround(MMA_simplify(e,full=False),digits = 14)
f = eff_hamiltonian_tayl[7,7]
#f = symround(MMA_simplify(f,full=False),digits = 14)

Calculating 0 out of [0, 1, 18, 19, 48, 49, 66, 67]...
Calculating 1 out of [0, 1, 18, 19, 48, 49, 66, 67]...
Calculating 18 out of [0, 1, 18, 19, 48, 49, 66, 67]...
Calculating 19 out of [0, 1, 18, 19, 48, 49, 66, 67]...
Calculating 48 out of [0, 1, 18, 19, 48, 49, 66, 67]...
Calculating 49 out of [0, 1, 18, 19, 48, 49, 66, 67]...
Calculating 66 out of [0, 1, 18, 19, 48, 49, 66, 67]...
Calculating 67 out of [0, 1, 18, 19, 48, 49, 66, 67]...

 Done! 


In [115]:
ham = (eff_hamiltonian_tayl_temp )
c_ham = conjugate(ham)
#eff_hamiltonian_tayl =   sg.matrix( ham._mathematica_().Plus(c_ham)._sage_() )/2
eff_hamiltonian_tayl = (ham +c_ham)/2

In [30]:
eff_hamiltonian_tayl = eff_hamiltonian_tayl_temp


In [39]:
m = 1
x = symround(f.subs(R_f=2.1,Deg1=np.sqrt(2)*C^m,Deg2=np.e*C^m,DEg=np.sqrt(5)*C^m,r_g=np.sqrt(3),gamma=0.3,r_f=0.1*np.sqrt(2), phi=np.pi/10,gamma_f=1.45,gamma_g=3))
x = x._mathematica_().Together().sage()
print('Numerator')
show(symround(x._mathematica_().Numerator()._sage_().expand()))
print('\n\nDenominator')
show(symround(x._mathematica_().Denominator()._sage_().expand()))

symround: Deleted coefficient 6.2e-17
symround: Deleted coefficient 4.8e-17
symround: Deleted coefficient 1.7e-18
symround: Deleted coefficient 1.7e-18
symround: Deleted coefficient 2.5e-18
Numerator


(0.053 - 0.81*I)*C^18*Omega^2 + (9.9 + 0.077*I)*C^17*Omega^2 + (3.7 + 46.*I)*C^16*Omega^2 + (23*I - 100)*C^15*Omega^2 - (56. + 110.*I)*C^14*Omega^2 - (63*I - 59)*C^13*Omega^2 + (38. + 13.*I)*C^12*Omega^2 + (2.5 + 13.*I)*C^11*Omega^2 - (2.5 - 2.3*I)*C^10*Omega^2 - (0.61 + 0.13*I)*C^9*Omega^2 - (0.038 + 0.078*I)*C^8*Omega^2 + (0.0036 - 0.0082*I)*C^7*Omega^2 + (0.00063 - 0.00023*I)*C^6*Omega^2 + (0.000032 + 0.000013*I)*C^5*Omega^2 + (5.4e-7 + 9.7e-7*I)*C^4*Omega^2 - (1.1e-9 - 1.7e-8*I)*C^3*Omega^2



Denominator


C^20 + (3.7 + 22.*I)*C^19 + (72*I - 200)*C^18 - (960*I + 592)*C^17 - (2624*I - 2560)*C^16 + (3456*I + 6784)*C^15 + (10240*I - 960)*C^14 + (3488*I - 8704)*C^13 - (3424*I + 4800)*C^12 - (36. + 2700.*I)*C^11 - (616*I - 720)*C^10 + (33*I + 254)*C^9 + (32. + 43.*I)*C^8 - (0.97 - 8.9*I)*C^7 - (0.86 - 0.79*I)*C^6 - (0.12 - 0.0071*I)*C^5 - (0.0076 + 0.0049*I)*C^4 - (0.00020 + 0.00047*I)*C^3 + (2.6e-6 - 0.000020*I)*C^2 + (2.6e-7 - 3.8e-7*I)*C + 4.2e-9 - 2.6e-9*I